import bcrypt from "bcryptjs";
import nodemailer from "nodemailer";
import { randomInt } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import type { RequestHandler } from "express";

const PIN_TTL_MS = 5 * 60 * 1000;

function getSupabaseAdminClient() {
  const supabaseUrl = process.env.SUPABASE_URL || "";
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "";
      if (!supabaseUrl || !serviceRoleKey) throw new Error("Missing Supabase admin credentials.");
        return createClient(supabaseUrl, serviceRoleKey, {
            auth: { autoRefreshToken: false, persistSession: false },
              });
              }

              function normalize(value: unknown): string {
                return typeof value === "string" ? value.replace(/\s+/g, "").toLowerCase() : "";
                }

                function escapeHtml(value: unknown): string {
                  return String(value ?? "")
                      .replace(/&/g, "&amp;")
                          .replace(/</g, "&lt;")
                              .replace(/>/g, "&gt;")
                                  .replace(/"/g, "&quot;")
                                      .replace(/'/g, "&#39;");
                                      }

                                      function maskEmail(email: string): string {
                                        const [localPart, domain] = email.split("@", 2);
                                          return localPart && domain ? `${localPart.slice(0, 2)}****@${domain}` : email;
                                          }

                                          const IDENTITY_ERROR = "Identité non vérifiée. Vérifiez le nom, le prénom, l’ID et l’UUID.";

                                          async function sendResetPin(email: string, name: string, pin: string) {
                                            const smtpUser = process.env.SMTP_USER;
                                              const smtpPass = process.env.SMTP_PASS;
                                                if (!smtpUser || !smtpPass) throw new Error("SMTP_USER et SMTP_PASS doivent être configurés.");

                                                  // Same transport defaults as server/routes/email.ts (the account-creation
                                                    // flow, which works in production): port 587 / secure=false unless the
                                                      // env vars say otherwise. Using different defaults here (465/secure=true)
                                                        // meant this flow silently used a different SMTP config than the one
                                                          // that's actually known to work with the configured Gmail account.
                                                            const transporter = nodemailer.createTransport({
                                                                host: process.env.SMTP_HOST || "smtp.gmail.com",
                                                                    port: Number(process.env.SMTP_PORT || 587),
                                                                        secure: process.env.SMTP_SECURE === "true",
                                                                            auth: { user: smtpUser, pass: smtpPass },
                                                                              });

                                                                                await transporter.sendMail({
                                                                                    from: `"Scoutisme Hassania" <${smtpUser}>`,
                                                                                        to: email,
                                                                                            subject: "Votre code PIN de récupération - Scoutisme Hassania",
                                                                                                text: `Bonjour, ${name},\n\nJe suis Adnane.ai. Votre code PIN de récupération est : ${pin}\n\nCe code expire dans 5 minutes et ne peut être utilisé qu’une seule fois. Saisissez-le sur la page de récupération pour choisir un nouveau mot de passe.`,
                                                                                                    html: `<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;color:#1f2937"><h2>Votre code PIN de récupération</h2><p>Bonjour ${escapeHtml(name)},</p><p>Voici le code PIN à saisir sur la page de récupération :</p><p style="font-size:30px;font-weight:bold;letter-spacing:8px;background:#f3f4f6;padding:16px;text-align:center">${escapeHtml(pin)}</p><p>Ce code expire dans 5 minutes et ne peut être utilisé qu’une seule fois.</p><p>Après validation du code, vous pourrez choisir un nouveau mot de passe.</p></div>`,
                                                                                                      });
                                                                                                      }

                                                                                                      async function findMember(adminClient: ReturnType<typeof getSupabaseAdminClient>, input: Record<string, unknown>) {
                                                                                                        const uuid = typeof input.uuid === "string" ? input.uuid.trim() : "";
                                                                                                          const firstName = normalize(input.first_name);
                                                                                                            const lastName = normalize(input.last_name);
                                                                                                              const generatedId = normalize(input.generated_id);
                                                                                                                if (!uuid || !firstName || !lastName || !generatedId) return null;

                                                                                                                  const { data: user, error } = await adminClient
                                                                                                                      .from("users")
                                                                                                                          .select("id, first_name, last_name, generated_id, email")
                                                                                                                              .eq("id", uuid)
                                                                                                                                  .maybeSingle();
                                                                                                                                    if (error) throw error;

                                                                                                                                      if (
                                                                                                                                          !user ||
                                                                                                                                              normalize(user.first_name) !== firstName ||
                                                                                                                                                  normalize(user.last_name) !== lastName ||
                                                                                                                                                      normalize(user.generated_id) !== generatedId ||
                                                                                                                                                          !normalize(user.email)
                                                                                                                                                            ) return null;

                                                                                                                                                              return user;
                                                                                                                                                              }

                                                                                                                                                              async function findValidPin(adminClient: ReturnType<typeof getSupabaseAdminClient>, email: string, pin: string) {
                                                                                                                                                                const { data: entry, error } = await adminClient
                                                                                                                                                                    .from("pins")
                                                                                                                                                                        .select("id, email, pin, generated_at, used")
                                                                                                                                                                            .eq("email", email)
                                                                                                                                                                                .order("generated_at", { ascending: false })
                                                                                                                                                                                    .limit(1)
                                                                                                                                                                                        .maybeSingle();
                                                                                                                                                                                          if (error) throw error;
                                                                                                                                                                                            if (!entry || entry.used) return null;
                                                                                                                                                                                              if (new Date(entry.generated_at).getTime() + PIN_TTL_MS <= Date.now()) return null;
                                                                                                                                                                                                return entry.pin === pin ? entry : null;
                                                                                                                                                                                                }

                                                                                                                                                                                                export const handleRequestPasswordReset: RequestHandler = async (req, res) => {
                                                                                                                                                                                                  try {
                                                                                                                                                                                                      const adminClient = getSupabaseAdminClient();
                                                                                                                                                                                                          const user = await findMember(adminClient, req.body || {});
                                                                                                                                                                                                              if (!user) return res.status(400).json({ ok: false, error: IDENTITY_ERROR });

                                                                                                                                                                                                                  const email = String(user.email).trim().toLowerCase();
                                                                                                                                                                                                                      const pin = String(randomInt(100000, 1000000));
                                                                                                                                                                                                                          const { error: insertError } = await adminClient.from("pins").insert({ email, pin, used: false });
                                                                                                                                                                                                                              if (insertError) {
                                                                                                                                                                                                                                    console.error("Erreur création PIN reset:", insertError);
                                                                                                                                                                                                                                          return res.status(500).json({ ok: false, error: "Impossible de créer le code de réinitialisation." });
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                        await sendResetPin(email, `${user.first_name || ""} ${user.last_name || ""}`.trim(), pin);
                                                                                                                                                                                                                                                            } catch (emailError) {
                                                                                                                                                                                                                                                                  console.error("Erreur SMTP Gmail (PIN reset):", emailError);
                                                                                                                                                                                                                                                                        const detail = emailError instanceof Error ? emailError.message : String(emailError);
                                                                                                                                                                                                                                                                              return res.status(500).json({ ok: false, error: `Impossible d’envoyer le code par e-mail. (${detail})` });
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                      return res.json({ ok: true, email: maskEmail(email), message: "Un code de réinitialisation a été envoyé par e-mail." });
                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                            console.error("Erreur handleRequestPasswordReset:", error);
                                                                                                                                                                                                                                                                                                return res.status(500).json({ ok: false, error: "Impossible de traiter la demande." });
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                  export const handleResetPassword: RequestHandler = async (req, res) => {
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                        const { pin, newPassword } = req.body || {};
                                                                                                                                                                                                                                                                                                            const normalizedPin = typeof pin === "string" ? pin.trim() : String(pin || "").trim();
                                                                                                                                                                                                                                                                                                                if (!/^\d{6}$/.test(normalizedPin)) {
                                                                                                                                                                                                                                                                                                                      return res.status(400).json({ ok: false, error: "Le code PIN doit contenir 6 chiffres." });
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                              const adminClient = getSupabaseAdminClient();
                                                                                                                                                                                                                                                                                                                                  const user = await findMember(adminClient, req.body || {});
                                                                                                                                                                                                                                                                                                                                      if (!user) return res.status(400).json({ ok: false, error: IDENTITY_ERROR });

                                                                                                                                                                                                                                                                                                                                          const email = String(user.email).trim().toLowerCase();
                                                                                                                                                                                                                                                                                                                                              const pinEntry = await findValidPin(adminClient, email, normalizedPin);
                                                                                                                                                                                                                                                                                                                                                  if (!pinEntry) return res.status(400).json({ ok: false, error: "Code invalide, expiré ou déjà utilisé." });

                                                                                                                                                                                                                                                                                                                                                      if (newPassword === undefined) {
                                                                                                                                                                                                                                                                                                                                                            return res.json({ ok: true, message: "Code PIN confirmé." });
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                    if (typeof newPassword !== "string" || newPassword.length < 6) {
                                                                                                                                                                                                                                                                                                                                                                          return res.status(400).json({ ok: false, error: "Le nouveau mot de passe doit contenir au moins 6 caractères." });
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                  const passwordHash = await bcrypt.hash(newPassword, 12);
                                                                                                                                                                                                                                                                                                                                                                                      const { error: updateError } = await adminClient.from("users").update({ password: passwordHash }).eq("id", user.id);
                                                                                                                                                                                                                                                                                                                                                                                          if (updateError) {
                                                                                                                                                                                                                                                                                                                                                                                                console.error("Erreur mise à jour mot de passe:", updateError);
                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(500).json({ ok: false, error: "Impossible de mettre à jour le mot de passe." });
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              const { data: consumedPin, error: consumeError } = await adminClient
                                                                                                                                                                                                                                                                                                                                                                                                                    .from("pins")
                                                                                                                                                                                                                                                                                                                                                                                                                          .update({ used: true })
                                                                                                                                                                                                                                                                                                                                                                                                                                .eq("id", pinEntry.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                      .eq("used", false)
                                                                                                                                                                                                                                                                                                                                                                                                                                            .select("id")
                                                                                                                                                                                                                                                                                                                                                                                                                                                  .maybeSingle();
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (consumeError || !consumedPin) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("Erreur consommation PIN reset:", consumeError);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return res.status(500).json({ ok: false, error: "Le mot de passe a été modifié, mais le code n’a pas pu être clôturé." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return res.json({ ok: true, message: "Mot de passe mis à jour avec succès." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error("Erreur handleResetPassword:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(500).json({ ok: false, error: "Impossible de mettre à jour le mot de passe." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
